version: v1.62.2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - revive
    - gosec
    - bodyclose
    - noctx
    - goconst
    - gocyclo
    - unconvert
    - unparam
